project:
  type: website

website:
  title: "115年國際職業衛生研究趨勢研討會"
#  navbar:
#    left:
#      - href: index.qmd
#        text: Home
#      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

