project:
  type: website
  output-dir: docs

website:
  title: "115年國際職業衛生趨勢研討會"
  page-navigation: false
  bread-crumbs: false
  back-to-top-navigation: true
#  page-footer:
#      center: "中國勞工安全衛生管理學會 2026-10-20"
      
  navbar:
    background: primary
    search: true




format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
